# Generated by Django 4.2.3 on 2023-12-21 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=89)),
                ('d', models.DateTimeField()),
                ('day', models.IntegerField()),
                ('costs', models.IntegerField()),
                ('comment', models.CharField(max_length=205)),
                ('sect', models.CharField(max_length=59)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=89)),
                ('d', models.DateTimeField()),
                ('day', models.IntegerField()),
                ('name', models.CharField(max_length=69)),
                ('booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=89)),
                ('name', models.CharField(max_length=59)),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('budget', models.IntegerField()),
                ('automate', models.BooleanField(default=True)),
                ('busket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='kasse.basket')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='kaufliste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busket', to='kasse.goods'),
        ),
    ]
