# Generated by Django 4.2.3 on 2023-12-21 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kasse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='sect',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='busket',
        ),
        migrations.AddField(
            model_name='basket',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buskets', to='kasse.sector'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='comment',
            field=models.CharField(blank=True, max_length=205, null=True),
        ),
    ]
