# Generated by Django 4.2.3 on 2023-12-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasse', '0003_remove_goods_day_goods_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='day',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='d',
        ),
    ]
