# Generated by Django 4.2.3 on 2023-11-19 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=85)),
                ('kategorie', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='autor',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.CreateModel(
            name='dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=85)),
                ('date', models.DateField()),
                ('actitivies', models.ManyToManyField(blank=True, related_name='dates', to='plan.task')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='classi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plan.kategories'),
        ),
    ]
