# Generated by Django 4.2.3 on 2023-11-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_kategories_rename_autor_task_author_remove_task_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
