# Generated by Django 4.2.3 on 2023-11-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
