# Generated by Django 4.2.3 on 2023-12-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_alter_task_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='weecklines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=85)),
                ('week', models.IntegerField()),
                ('line', models.CharField(max_length=89)),
            ],
        ),
    ]
